### ISSUE TITLE
Contributing.md

### ISSUE THREAD

**Issue by Devansh-Singh-Parmar** [danger-ahead/nextjs_dev_folio#2]
Please assign this issue to me, I want to create contributing.md to this proj

**Comment by danger-ahead** [comment]
@Devansh-Singh-Parmar sure! Go ahead!

**Comment by Durgeshsejekar** [comment]
I want to work on this issue so please can u assign me.

**Comment by Devansh-Singh-Parmar** [comment]
I am already working.
