### ISSUE TITLE
pnpm installation - Clarity Needed

### ISSUE THREAD

**Issue by thought-train** [danger-ahead/nextjs_dev_folio#6]
When I was cloning the repo,I encountered an issue with pnpm and just thought it was a typo(i didn't know about pnpm,pardon 🙃) and now I think it'd be better if we just add the command `npm install -g pnpm` before the `npm install` command.

Please don't dismiss this,I'll submit PR in 15 min.

**Comment by danger-ahead** [comment]
Yes, you can add a note for that. Maybe a comment?
